# Generated by Django 5.1.4 on 2025-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=12)),
                ('phone_no', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('no_of_vacancies', models.IntegerField()),
                ('job_location_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('pay_and_benefits', models.TextField()),
                ('benefits', models.TextField()),
                ('job_description', models.TextField()),
            ],
        ),
    ]
