# Generated by Django 5.1.4 on 2025-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_post',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Paused', 'Paused')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='company_logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
